# Generated by Django 5.1.6 on 2025-02-24 14:41

import cloudinary.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value_exp', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('achievement_type', models.CharField(choices=[('level', 'Completed Level'), ('exp', 'Gained Experience')], max_length=255)),
                ('achievement_image', cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dvo1jlfym/image/upload/v1740378927/default_item_dw3tqa.png', max_length=255, null=True, verbose_name='achievements/')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('skill_image', cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dvo1jlfym/image/upload/v1740378927/default_item_dw3tqa.png', max_length=255, null=True, verbose_name='skills/')),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=1000)),
                ('task_status', models.CharField(choices=[('completed', 'Completed'), ('not_completed', 'Not completed')], db_index=True, default='not_completed', max_length=255)),
                ('value_exp', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('quest_status', models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In progress'), ('not_completed', 'Not completed'), ('failed', 'Failed')], default='not_completed', max_length=255)),
                ('value_exp', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.skill')),
                ('tasks', models.ManyToManyField(blank=True, to='main.task')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_number', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('name', models.CharField(default='NONAME lvl.<django.db.models.fields.IntegerField>', max_length=255)),
                ('required_exp', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('level_image', cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dvo1jlfym/image/upload/v1740378324/level_default_w5guht.jpg', max_length=255, null=True, verbose_name='levels/')),
                ('achievement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.achievement')),
                ('quests', models.ManyToManyField(blank=True, to='main.quest')),
                ('tips', models.ManyToManyField(blank=True, to='main.tip')),
            ],
            options={
                'ordering': ['level_number'],
            },
        ),
    ]
